### ISSUE TITLE
Detect compilation errors and stop the process on some error

### ISSUE THREAD

**Issue by cwchentw** [gnustep/tools-scripts#3]
It is not totally error-free to compile GNUstep. For instance, a recent [issue](https://github.com/msys2/MINGW-packages/issues/6986) of binutils prevents lib-base from compilation on MinGW64 of MSYS2. Nevertheless, most of current build scripts in this repo assume the compilation process is correct, which is not always the case. Consider to add error detection after each step, stopping the process when some unexcepted error happens.

**Comment by gcasa** [comment]
Which script are you referring to?   Also, this issue has been fixed with respect to binutils.  NSObject was patched to correct this.

**Comment by cwchentw** [comment]
I ran [build-mingw64_nt](https://github.com/gnustep/tools-scripts/blob/master/build-mingw64_nt) with the latest release tarballs of GNUstep on a recent MSYS2 environment. I think the `binutils` issue was not fixed when those tarballs were released.

BTW, is it recommended to compile GNUstep with the master branch of its repo? Or should we compile it with its latest tarballs?

**Comment by gcasa** [comment]
There hasn't been a new release since the patch, so the change is not in the latest tarballs.  The best thing to do is use the gnustep-web-install.... this will download all of the latest stuff and build.  Please try that and let me know if there is still an error in base.

**Comment by cwchentw** [comment]
`gnustep-web-install` works like a charm except minor post install issue. Here is the vanilla message:

```
================ Post Installation ================
GNUmakefile:31: *** You need to set GNUSTEP_MAKEFILES before compiling!。 停止。
GNUmakefile:30:
GNUmakefile:31: Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!
GNUmakefile:32: Perhaps gnustep-make is not properly installed,
GNUmakefile:33: so gnustep-config is not in your PATH.
GNUmakefile:34:
GNUmakefile:35: Your PATH is currently /mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
GNUmakefile:36:
GNUmakefile:41: *** You need to set GNUSTEP_MAKEFILES before compiling!。 停止。 (i.e. stop it.)
./tools-scripts/post-install-mingw64_nt: 列 11: defaults：命令找不到 (i.e. command not found)
Done...
```

It doesn't affect compiled GNUstep programs. Hence, I think the issue doesn't matter greatly.
